import UserFinancial from '@/app/(hydrogen)/user-financial/page';
import { create } from 'lodash';

export const routes = {
   searchAndFilter: {
      realEstate: '/search/real-estate',
      nft: '/search/nft',
      flight: '/search/flight',
   },
   support: {
      expenditure: '/expenditure',
      dashboard: '/support',
      inbox: '/support/inbox',
      supportCategory: (category: string) => `/support/inbox/${category}`,
      messageDetails: (id: string) => `/support/inbox/${id}`,
      snippets: '/support/snippets',
      createSnippet: '/support/snippets/create',
      viewSnippet: (id: string) => `/support/snippets/${id}`,
      editSnippet: (id: string) => `/support/snippets/${id}/edit`,
      templates: '/support/templates',
      createTemplate: '/support/templates/create',
      viewTemplate: (id: string) => `/support/templates/${id}`,
      editTemplate: (id: string) => `/support/templates/${id}/edit`,
   },
   logistics: {
      dashboard: '/logistics',
      shipmentList: '/logistics/shipments',
      customerProfile: '/logistics/customer-profile',
      createShipment: '/logistics/shipments/create',
      editShipment: (id: string) => `/logistics/shipments/${id}/edit`,
      shipmentDetails: (id: string) => `/logistics/shipments/${id}`,
      tracking: (id: string) => `/logistics/tracking/${id}`,
   },
   appointment: {
      dashboard: '/appointment',
      appointmentList: '/appointment/list',
   },
   crm: {
      dashboard: '/crm',
   },
   affiliate: {
      dashboard: 'https://isomorphic-dnd.vercel.app',
   },
   storeAnalytics: {
      dashboard: '/store-analytics',
   },
   bidding: {
      dashboard: '/bidding',
   },
   executive: {
      dashboard: '/executive',
   },
   project: {
      dashboard: '/project',
   },
   socialMedia: {
      dashboard: '/social-media',
   },
   jobBoard: {
      dashboard: '/job-board',
      jobFeed: '/job-board/feed',
   },
   analytics: '/analytics',
   // financial: {
   //    dashboard: '/financial',
   // },
   file: {
      dashboard: '/file',
      manager: '/file-manager',
      upload: '/file-manager/upload',
      create: '/file-manager/create',
   },
   pos: {
      index: '/point-of-sale',
   },
   eventCalendar: '/event-calendar',
   rolesPermissions: '/roles-permissions',
   invoice: {
      home: '/invoice',
      create: '/invoice/create',
      details: (id: string) => `/invoice/${id}`,
      edit: (id: string) => `/invoice/${id}/edit`,
      builder: '/invoice/builder',
   },
   imageViewer: '/image-viewer',
   widgets: {
      cards: '/widgets/cards',
      icons: '/widgets/icons',
      charts: '/widgets/charts',
      maps: '/widgets/maps',
      banners: '/widgets/banners',
   },
   tables: {
      collapsible: '/tables/collapsible',
      enhanced: '/tables/enhanced',
      pagination: '/tables/pagination',
      search: '/tables/search',
      stickyHeader: '/tables/sticky-header',
      resizable: '/tables/resizable',
      pinning: '/tables/pinning',
      dnd: '/tables/dnd',
   },
   multiStep: '/multi-step',
   forms: {
      profileSettings: '/forms/profile-settings',
      notificationPreference: '/forms/profile-settings/notification',
      personalInformation: '/forms/profile-settings/profile',
      newsletter: '/forms/newsletter',
   },
   emailTemplates: '/email-templates',
   profile: '/profile',
   changePassword: '/change-password',
   welcome: '/welcome',
   comingSoon: '/coming-soon',
   accessDenied: '/access-denied',
   maintenance: '/maintenance',
   blank: '/blank',
   auth: {
      signUp1: '/auth/sign-up-1',
      signUp2: '/auth/sign-up-2',
      signUp3: '/auth/sign-up-3',
      signUp4: '/auth/sign-up-4',
      signUp5: '/auth/sign-up-5',
      // sign in
      signIn1: '/auth/sign-in-1',
      signIn2: '/auth/sign-in-2',
      signIn3: '/auth/sign-in-3',
      signIn4: '/auth/sign-in-4',
      signIn5: '/auth/sign-in-5',
      // forgot password
      forgotPassword1: '/auth/forgot-password-1',
      forgotPassword2: '/auth/forgot-password-2',
      forgotPassword3: '/auth/forgot-password-3',
      forgotPassword4: '/auth/forgot-password-4',
      forgotPassword5: '/auth/forgot-password-5',
      // OTP
      otp1: '/auth/otp-1',
      otp2: '/auth/otp-2',
      otp3: '/auth/otp-3',
      otp4: '/auth/otp-4',
      otp5: '/auth/otp-5',
   },
   dashboardAdmin: '/dashboard-admin',
   dashboardPilot: '/dashboard-pilot',
   dashboardLocalManager: '/dashboard-local-manager',
   signIn: '/signin',
   forgotPassword: '/forgot-password',
   resetPassword: '/reset-password',
   UserFinancial: '/user-financial',
   users: '/users',
   settings: '/settings',
   operational: {
      services: '/operational/services',
      serviceDetails: (id: string) => `/operational/services/${id}`,
      createService: '/operational/services/create',
      editService: (id: string) => `/operational/services/${id}/edit`,
      contracts: '/operational/contracts',
      contractDetails: (id: string) => `/operational/contracts/${id}`,
      createContract: '/operational/contracts/create',
   },
   financial: {
      expenditure: '/financial/expenses',
      addExpenditure: '/financial/spendings',
      expenses: '/financial/expenses',
      payrolls: '/financial/payrolls',
      payrollsCreate: '/financial/payrolls/create',
      payrollsEdit: (id: string) => `/financial/payrolls/edit/${id}`,
      payrollsClone: (id: string) => `/financial/payrolls/clone/${id}`,
      createExpense: '/financial/expenses/create',
      expenseDetails: (id: string) => `/financial/expenses/${id}`,
      editExpense: (id: string) => `/financial/expenses/${id}/edit`,
      revenues: '/financial/revenues',
      createRevenue: '/financial/revenues/create',
      revenueDetails: (id: string) => `/financial/revenues/${id}`,
      editRevenue: (id: string) => `/financial/revenues/${id}/edit`,
   },
   producers: '/producers',
   contracts: '/contracts',
   production: '/production',
};
